name: pytorch-1.4
channels:
  - tensorly
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_2
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cython=0.29.24=py37hdbfa776_0
  - easydict=1.9=py_0
  - freetype=2.10.4=h5ab3b9f_0
  - icu=67.1=he1b5a44_0
  - intel-openmp=2021.2.0=h06a4308_610
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py37hc928c03_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37h1d35a4c_1
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.1=py37h93e21f0_0
  - numpy-base=1.20.1=py37h7d8b39e_0
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.0.1=py37h06a4308_0
  - pycocotools=2.0.2=py37h8f50634_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.10=hdb3f193_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tensorly=0.6.0=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.1=py37h4abf009_0
  - tqdm=4.60.0=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
prefix: /home/robert80203/.conda/envs/pytorch-1.4
