DATASET:
    upsamplingFactor: 4 # from heatmaps (64 x 64) to RGB (256 x 256)
    duration: 600 
    heatmapSize: 64
    imgSize: 256
    rangeSize: 64
    azimuthSize: 64
    elevationSize: 8
    numKeypoints: 14
    numFrames: 8 # num of chirps in one frame to be processed
    numGroupFrames: 8 # num of frames to be processed
    numChirps: 16 # num of chirps captured by radar sensors, should always be 16
    dataDir: '' #'../radar_skeleton_estimation_iwr1843/data/20220623'
    testName: [15, 16, 38, 40, 41, 42,
               17, 39,  244, 245, 246, 249, 250, 251, 252, 253, 254,
               247, 248, 255, 256]
    valName: [1, 14, 34, 57, 65,  98,
              56, 99, 159, 178,
              101, 120, 137, 156, 161, 164, 181, 194, 197, 205, 257]
    trainName: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 18, 19, 20, 21, 
                22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 35, 36, 37, 43, 
                44, 45, 46, 47, 48, 49, 50, 51, 52, 58, 59, 60, 61, 62, 
                63, 64, 66, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 83, 
                84, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                31, 32, 53, 54, 55, 67, 68, 69, 70, 72, 85, 86, 100, 157, 158, 
                160, 167, 168, 169, 170, 177, 179, 180, 187, 188, 189, 190, 
                228, 229, 230, 259, 260, 263, 264, 269, 270, 273, 274,
                102, 103, 104, 105, 106, 107, 108, 109, 110, 119, 121, 122, 
                123, 124, 133, 134, 135, 138, 147, 148, 149, 150, 151, 152, 
                153, 154, 155, 162, 163, 165, 166, 171, 172, 173, 174, 175, 
                176, 182, 183, 184, 185, 186, 191, 192, 193, 195, 196, 198, 
                199, 200, 201, 202, 203, 204, 206, 207, 208, 209, 210, 211, 
                212, 213, 215, 216, 223, 224, 225, 226, 231, 232, 233, 234, 
                235, 236, 258, 261, 262, 265, 266, 267, 268, 271, 272, 275, 
                276]
    idxToJoints:
        ["R_Hip", "R_Knee", "R_Ankle", "L_Hip", "L_Knee", 
         "L_Ankle", "Neck", "Head", "L_Shoulder", "L_Elbow", 
         "L_Wrist", "R_Shoulder", "R_Elbow", "R_Wrist"]
MODEL:
    numFilters: 32
TRAINING:
    batchSize: 20
    epochs: 200
    lr: 0.0001
    warmupEpoch: -1
    warmupGrowth: 1.005
    lrDecay: 0.999
    lrDecayIter: 2000
    lossDecay: -1
    optimizer: "adam"
TEST:
    batchSize: 32
    plotImgDir: '' #"20220623"
SETUP:
    numWorkers: 4